### PR TITLE
feature: index `unicode` fields for icons for enable unicode search

### PR DESCRIPTION
**Pull request by grimen**
Additional: Grouped operations by the comments to make the code a bit
more readable.

### CODE REVIEW

**Comment by grimen** [comment]
fixes #50

**Comment by redox** [comment]
LGTM :+1:

**Comment by thomaspark** [comment]
Merged and re-index.

@redox, is there a way to set fuzziness per attribute? I think it's preferable to have exact matching on hex searches.

**Comment by redox** [comment]
@thomaspark sorry for being late here. Yes we can use the [`disableTypoToleranceOnAttributes`](https://www.algolia.com/doc/javascript#param-disableTypoToleranceOnAttributes-2) to disable the typo-tolerance on some attributes:

```js
    index.setSettings({
      'attributesToIndex': ["name", "tags", "unicode"],
      'disableTypoToleranceOnAttributes': ['unicode'],
      'customRanking': ["asc(name)"],
      'queryType': 'prefixAll'
    });
```

Let me know what you guys think! @thomaspark @grimen

**Pull request merged**
