### PR TITLE
adding copy method with url change

### PR DESCRIPTION
**Pull request by horans**
allow user directly switch to certain copy method from url parameters.
the new setCopy() works just like setLibrary().

### CODE REVIEW

**Comment by thomaspark** [comment]
@horans, this is fantastic. Thanks for the contribution!

**Comment by thomaspark** [comment]
Spotted a small bug: when you delete the `copy` argument in the URL, the "markup" button is highlighted but what's actually copied is whatever was last selected.

**Comment by horans** [comment]
i guess its something to do with line 28:
`setState("library", qs.library);`
i added the line underneath without thinking:
`setState("copy", qs.copy);`

then, the "state[copy]" will turn "undefined" if the query string is not having "copy=". (same as the "state[library]")

how about change these two lines into:
`setState("library", qs.library || "all");
setState("copy", qs.copy || "markup");`

**Comment by thomaspark** [comment]
That should do the trick, and makes lines 40 and 76 redundant.

**Pull request merged**
