### PR TITLE
material: missing SVG Font file (*.svg)

### PR DESCRIPTION
**Pull request by grimen**
Note: Using fork repo in wait for merged pull request.

### CODE REVIEW

**Comment by thomaspark** [comment]
Would prefer to wait for that PR (https://github.com/google/material-design-icons/pull/282) to be merged to official.

**Comment by grimen** [comment]
@thomaspark Yes, I am working on it - review cycles there takes some time it seems.

**Comment by grimen** [comment]
@thomaspark Material Icons Font now have SVG font! https://github.com/google/material-design-icons/pull/282#issuecomment-174543843. Proceed with this?

**Comment by thomaspark** [comment]
Great news. As soon as I update material-design-icons, we can proceed with "copy as SVG".

Testing v2.2.0 and having issues with the new icons displaying however:  https://github.com/google/material-design-icons/issues/311

**Comment by grimen** [comment]
@thomaspark Any update on this?

**Comment by thomaspark** [comment]
Just updated to v2.2.1 in 0854341d64d92cf87fe5078df2d7a277ccc7a920, which enables us to move forward with SVG copy option.

**Pull request closed without merging**
